# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-19 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='moment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xiaoxi', models.CharField(max_length=200)),
                ('user_name', models.CharField(max_length=20)),
                ('kind', models.CharField(max_length=20)),
            ],
        ),
    ]
