# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-19 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_moment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moment',
            name='kind',
            field=models.CharField(choices=[('技术', '技术'), ('新闻', '新闻'), ('财务', '财务'), ('人力', '人力'), ('团队', '团队')], default=('技术', '技术'), max_length=20),
        ),
        migrations.AlterField(
            model_name='moment',
            name='user_name',
            field=models.CharField(default='匿名', max_length=20),
        ),
    ]
